"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['coffeegrindsize.py']
APP_NAME='Coffee Particle Grind Size Distribution'
DATA_FILES = []
OPTIONS = {}

setup(
    app_name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['pillow','numpy','pandas','matplotlib'],
)
