"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['coffeegrindsize.py']
APP_NAME='Coffee Particle Grind Size Distribution'
DATA_FILES = []
OPTIONS = {
    'plist': {
        'CFBundleName': 'CoffeeGrindSize',
        'CFBundleShortVersionString':'1.0.0', 
        'CFBundleVersion': '1.0.0', 
        'CFBundleIdentifier':'com.coffeeadastra.coffeegrindsize', 
        'NSHumanReadableCopyright': '@ Jonathan Gagné'
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['tkinter','pillow','numpy','pandas','matplotlib'],
)
